<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <UseWPF>true</UseWPF>
    <AssemblyName>FarmReel</AssemblyName>
    <RootNamespace>FarmReel.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FarmReel.Core\FarmReel.Core.csproj" />
    <ProjectReference Include="..\FarmReel.Automation\FarmReel.Automation.csproj" />
  </ItemGroup>

</Project>
